pull_requests:
  do_not_increment_build_number: true
environment:
  repo_token:
    secure: 2IfF4fXwHC6ix7KXkbvghzUT7zFzOjWWQKypfm/efc7XrUAHZdplFuLU08JJ37yk
skip_branch_with_pr: true
image: Previous Visual Studio 2017
configuration: Release
shallow_clone: true
cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
install:
  - choco install fciv doxygen.portable codecov
before_build:
  - nuget restore MapDiffBot.sln
build:
  project: MapDiffBot.sln
  parallel: false
  verbosity: minimal
  publish_nuget: true
test_script:
  - set path=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow;%path%
  - copy "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions\appveyor.*" "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions" /y
  - vstest.console /logger:Appveyor "MapDiffBot.Tests\bin\Release\MapDiffBot.Tests.dll" /Enablecodecoverage /Settings:"Tools/CoverageExclusions.runsettings"
after_test:
  - ps: Tools/UploadCoverage.ps1
  - ps: Tools/BuildDox.ps1
