pull_requests:
  do_not_increment_build_number: true
environment:
  repo_token:
    secure: lJNGAXwiB5HlWdthz3K4PetqpTG5IEAyRgKaiKxFMQ8HW8CcOjRtB97B05op7BsK
  snk_passphrase:
    secure: dsRGlNewYn/JoycPaMoxLCrb3wkL31RsdU7Xwbo7TIAmClwShCVWeRPN+eGA+fMZX12MDNRBs8Fws4IxqLKQ36thQo6p2B+kPksAUJiAOR5QKJoT6nt8JB1wBMFS2kH4
skip_branch_with_pr: true
image: Previous Visual Studio 2017
configuration: Release
shallow_clone: true
cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
install:
  - choco install fciv doxygen.portable codecov
before_build:
  - nuget restore TGStationServer3.sln
build:
  project: MapDiffBot.sln
  parallel: false
  verbosity: minimal
  publish_nuget: true
test_script:
  - set path=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow;%path%
  - copy "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions\appveyor.*" "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions" /y
  - vstest.console /logger:Appveyor "MapDiffBot.Tests\bin\Release\MapDiffBot.Tests.dll" /Enablecodecoverage /Settings:"Tools/CoverageExclusions.runsettings"
after_test:
  - ps: Tools/UploadCoverage.ps1
  - ps: Tools/BuildDox.ps1
deploy:
  - provider: GitHub
    release: "MapDiffBot-v$(TGSVersion)"
    description: 'Generated by appveyor CI. To be filled by maintainer...'
    auth_token:
      secure: lJNGAXwiB5HlWdthz3K4PetqpTG5IEAyRgKaiKxFMQ8HW8CcOjRtB97B05op7BsK
    artifact: TGS3Server,MD5SHA1Server,TGS3Client,MD5SHA1Client,TGS3ServerConsole,MD5SHA1ServerConsole
    draft: true
    on:
      MDBDeploy: "Do it."
  - provider: NuGet
    api_key:
      secure: bedsYuLMqGREzkVkJqRx+BTMgOvDO76tgaNc8sW5E3Ao6iw8oGHdJ/BZov8y0iKa
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      NugetDeploy: "Do it."
